version: '3.9'

services:
  db:
    image: bitnami/postgresql:15.2.0
    restart: always
    environment:
      - POSTGRESQL_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: nest-products-postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-products
    environment:
      - PORT=${PORT}
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./src:/app/src
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-products-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - 5050:80
    depends_on:
      - db

volumes:
  postgres:
    driver: local
